# Game Settings
WIDTH = 800
HEIGHT = 600
FPS = 60

# Colors

BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255, 255)

# Player Settings
PLAYER_SPEED = 5
PLAYER_JUMP = 17
PLAYER_WEAPONS = ["HEAVY_MACHINE_GUN", "FIRE_GUN", "SHOT_GUN", "ROCKET_GUN", "BOMB_GUN",
                  "MORTAR_GUN", "LAZER_GUN", "SUPER_LAZER"]
# Enemie Settings

ENEMIE_WEAPONS = ["KNIFE_ONLY", "BOMB", "SHIELD_COLT", "SHIELD_ONLY", "ROCKET", "GUN", "MORTAR",
                  "KNIFE_JUMPING", "MOTOCYCLING", "COLT"]
